;; theme file, written Mon Oct  9 12:03:48 JST 2000
;; created by sawfish-themer -- DO NOT EDIT!

(require 'make-theme)

(let
    ((patterns-alist
      '(
        ("font-colors"
         (inactive . "#7ba5ff")
         (focused . "#ffffff"))
        ("ltitle-colors"
         (inactive . "#2963b5")
         (focused . "#5294f7"))
        ("rtitle-colors"
         (inactive . "#2963b5")
         (focused . "#3173d6"))
        ("title-image"
         (inactive "title-inactive.png")
         (focused "title.png"))
        ("close-image"
         (inactive "close-inactive.png")
         (focused "close.png")
         (highlighted "close-highlighted.png")
         (clicked "close-clicked.png"))
        ("icon-image"
         (inactive "iconify-inactive.png")
         (focused "iconify.png")
         (highlighted "iconify-highlighted.png")
         (clicked "iconify-clicked.png"))
        ("max-image"
         (inactive "maximize-inactive.png")
         (focused "maximize.png")
         (highlighted "maximize-highlighted.png")
         (clicked "maximize-clicked.png"))
        ("menu-image"
         (inactive "menu-inactive.png")
         (focused "menu.png")
         (highlighted "menu-highlighted.png")
         (clicked "menu-clicked.png"))
        ("top-image"
         (inactive "tborder-inactive.png")
         (focused "tborder.png"))
        ("top-left-image"
         (inactive "tlcorner-inactive.png")
         (focused "tlcorner.png"))
        ("top-right-image"
         (inactive "trcorner-inactive.png")
         (focused "trcorner.png"))
        ("bottom-left-image"
         (inactive "blcorner-inactive.png")
         (focused "blcorner.png"))
        ("bottom-right-image"
         (inactive "brcorner-inactive.png")
         (focused "brcorner.png"))
        ("bottom-image"
         (inactive "bborder-inactive.png")
         (focused "bborder.png"))
        ("left-image"
         (inactive "lborder-inactive.png")
         (focused "lborder.png"))
        ("right-image"
         (inactive "rborder-inactive.png")
         (focused "rborder.png"))
        ("left-shaded-image"
         (inactive "lshaded-inactive.png")
         (focused "lshaded.png"))
        ("right-shaded-image"
         (inactive "rshaded-inactive.png")
         (focused "rshaded.png"))
        ))

     (frames-alist
      '(("frame"
         ((class . title)
          (text . window-name)
	  ;(font . "-adobe-helvetica-bold-r-normal-*-*-120-*-*-p-*-*-*")
          (x-justify . 22)
          (y-justify . center)
          (cursor . left_ptr)
          (left-edge . 0)
          (right-edge . 135)
          (top-edge . -22)
          (height . 22)
          (foreground . "font-colors")
          (background . "ltitle-colors"))
         ((class . title)
          (right-edge . 0)
          (top-edge . -22)
          (width . 110)
          (height . 22)
          (background . "rtitle-colors"))
         ((class . title)
          (right-edge . 110)
          (top-edge . -22)
          (background . "title-image"))
         ((class . menu-button)
          (cursor . left_ptr)
          (left-edge . 0)
          (top-edge . -21)
          (background . "menu-image"))
         ((class . close-button)
          (cursor . left_ptr)
          (right-edge . 0)
          (top-edge . -21)
          (background . "close-image"))
         ((class . maximize-button)
          (cursor . left_ptr)
          (right-edge . 20)
          (top-edge . -21)
          (background . "max-image"))
         ((class . iconify-button)
          (cursor . left_ptr)
          (right-edge . 37)
          (top-edge . -21)
          (background . "icon-image"))
         ((class . top-border)
          (left-edge . 0)
          (right-edge . 0)
          (top-edge . -22)
          (background . "top-image"))
         ((class . top-left-corner)
          (left-edge . -4)
          (top-edge . -22)
          (background . "top-left-image"))
         ((class . top-right-corner)
          (right-edge . -4)
          (top-edge . -22)
          (background . "top-right-image"))
         ((class . left-border)
          (left-edge . -4)
          (top-edge . 0)
          (bottom-edge . 0)
          (background . "left-image"))
         ((class . right-border)
          (right-edge . -4)
          (top-edge . 0)
          (bottom-edge . 0)
          (background . "right-image"))
         ((class . bottom-border)
          (left-edge . 0)
          (right-edge . 0)
          (bottom-edge . -4)
          (background . "bottom-image"))
         ((class . bottom-left-corner)
          (left-edge . -4)
          (bottom-edge . -4)
          (background . "bottom-left-image"))
         ((class . bottom-right-corner)
          (right-edge . -4)
          (bottom-edge . -4)
          (background . "bottom-right-image")))
        ("shaped-frame"
         ((class . title)
          (text . window-name)
	  ;(font . "-adobe-helvetica-bold-r-normal-*-*-120-*-*-p-*-*-*")
          (x-justify . 22)
          (y-justify . center)
          (cursor . left_ptr)
          (left-edge . 0)
          (right-edge . 135)
          (top-edge . -22)
          (height . 22)
          (foreground . "font-colors")
          (background . "ltitle-colors"))
         ((class . title)
          (right-edge . 0)
          (top-edge . -22)
          (width . 110)
          (height . 22)
          (background . "rtitle-colors"))
         ((class . title)
          (right-edge . 110)
          (top-edge . -22)
          (background . "title-image"))
         ((class . menu-button)
          (cursor . left_ptr)
          (left-edge . 0)
          (top-edge . -21)
          (background . "menu-image"))
         ((class . close-button)
          (cursor . left_ptr)
          (right-edge . 0)
          (top-edge . -21)
          (background . "close-image"))
         ((class . maximize-button)
          (cursor . left_ptr)
          (right-edge . 20)
          (top-edge . -21)
          (background . "max-image"))
         ((class . iconify-button)
          (cursor . left_ptr)
          (right-edge . 37)
          (top-edge . -21)
          (background . "icon-image"))
         ((class . title)
          (left-edge . 0)
          (right-edge . 0)
          (top-edge . -22)
          (background . "top-image"))
         ((class . title)
          (left-edge . 0)
          (right-edge . 0)
          (top-edge . -1)
          (background . "top-image"))
         ((class . title)
          (left-edge . -4)
          (top-edge . -22)
          (background . "left-shaded-image"))
         ((class . title)
          (right-edge . -4)
          (top-edge . -22)
          (background . "right-shaded-image")))
        ("transient-frame"
         ((class . title)
          (text . window-name)
	  ;(font . "-adobe-helvetica-bold-r-normal-*-*-120-*-*-p-*-*-*")
          (x-justify . 22)
          (y-justify . center)
          (cursor . left_ptr)
          (left-edge . 0)
          (right-edge . 135)
          (top-edge . -22)
          (height . 22)
          (foreground . "font-colors")
          (background . "ltitle-colors"))
         ((class . title)
          (right-edge . 0)
          (top-edge . -22)
          (width . 110)
          (height . 22)
          (background . "rtitle-colors"))
         ((class . title)
          (right-edge . 110)
          (top-edge . -22)
          (background . "title-image"))
         ((class . menu-button)
          (cursor . left_ptr)
          (left-edge . 0)
          (top-edge . -21)
          (background . "menu-image"))
         ((class . close-button)
          (cursor . left_ptr)
          (right-edge . 0)
          (top-edge . -21)
          (background . "close-image"))
         ((class . top-border)
          (left-edge . 0)
          (right-edge . 0)
          (top-edge . -22)
          (background . "top-image"))
         ((class . top-left-corner)
          (left-edge . -4)
          (top-edge . -22)
          (background . "top-left-image"))
         ((class . top-right-corner)
          (right-edge . -4)
          (top-edge . -22)
          (background . "top-right-image"))
         ((class . left-border)
          (left-edge . -4)
          (top-edge . 0)
          (bottom-edge . 0)
          (background . "left-image"))
         ((class . right-border)
          (right-edge . -4)
          (top-edge . 0)
          (bottom-edge . 0)
          (background . "right-image"))
         ((class . bottom-border)
          (left-edge . 0)
          (right-edge . 0)
          (bottom-edge . -4)
          (background . "bottom-image"))
         ((class . bottom-left-corner)
          (left-edge . -4)
          (bottom-edge . -4)
          (background . "bottom-left-image"))
         ((class . bottom-right-corner)
          (right-edge . -4)
          (bottom-edge . -4)
          (background . "bottom-right-image")))
        ("shaped-transient-frame"
         ((class . title)
          (text . window-name)
	  ;(font . "-adobe-helvetica-bold-r-normal-*-*-120-*-*-p-*-*-*")
          (x-justify . 22)
          (y-justify . center)
          (cursor . left_ptr)
          (left-edge . 0)
          (right-edge . 135)
          (top-edge . -22)
          (height . 22)
          (foreground . "font-colors")
          (background . "ltitle-colors"))
         ((class . title)
          (right-edge . 0)
          (top-edge . -22)
          (width . 110)
          (height . 22)
          (background . "rtitle-colors"))
         ((class . title)
          (right-edge . 110)
          (top-edge . -22)
          (background . "title-image"))
         ((class . menu-button)
          (cursor . left_ptr)
          (left-edge . 0)
          (top-edge . -21)
          (background . "menu-image"))
         ((class . close-button)
          (cursor . left_ptr)
          (right-edge . 0)
          (top-edge . -21)
          (background . "close-image"))
         ((class . title)
          (left-edge . 0)
          (right-edge . 0)
          (top-edge . -22)
          (background . "top-image"))
         ((class . title)
          (left-edge . 0)
          (right-edge . 0)
          (top-edge . -1)
          (background . "top-image"))
         ((class . title)
          (left-edge . -4)
          (top-edge . -22)
          (background . "left-shaded-image"))
         ((class . title)
          (right-edge . -4)
          (top-edge . -22)
          (background . "right-shaded-image")))))

     (mapping-alist
      '((default . "frame")
        (transient . "transient-frame")
        (shaped . "shaped-frame")
        (shaped-transient . "shaped-transient-frame")
        (unframed . "nil")))

     (theme-name 'WhistlerK))

  (add-frame-style
   theme-name (make-theme patterns-alist frames-alist mapping-alist))
  (when (boundp 'mark-frame-style-editable)
    (mark-frame-style-editable theme-name)))
