-- This file has been generated by Ion. Do not edit.
return {
    [1] = "menu.mainmenu:session/exit",
    [2] = "menu.mainmenu:session/restart",
    [3] = "man:",
    [4] = "yesno:y",
    [5] = "menu.mainmenu:styles/look_greenlight",
}

