-- This file has been generated by Ion. Do not edit.
return {
    [0] = {
        ["type"] = "WRootWin",
        ["name"] = "WRootWin",
        ["managed"] = {
            [1] = {
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS",
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1024,
                    ["h"] = 768,
                },
                ["switchto"] = true,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<1>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1024,
                            ["h"] = 768,
                        },
                        ["split_tree"] = {
                            ["tls"] = 753,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<2>",
                                    ["managed"] = {
                                        [1] = {
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW",
                                            ["geom"] = {
                                                ["y"] = 18,
                                                ["x"] = 1,
                                                ["w"] = 1022,
                                                ["h"] = 734,
                                            },
                                            ["switchto"] = true,
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["windowid"] = 8388621,
                                                    ["checkcode"] = 1,
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["y"] = 1,
                                                        ["x"] = 2,
                                                        ["w"] = 1018,
                                                        ["h"] = 732,
                                                    },
                                                    ["level"] = 0,
                                                },
                                            },
                                            ["level"] = 0,
                                        },
                                        [2] = {
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW<2>",
                                            ["hidden"] = true,
                                            ["geom"] = {
                                                ["y"] = 18,
                                                ["x"] = 1,
                                                ["w"] = 1022,
                                                ["h"] = 734,
                                            },
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["windowid"] = 12582925,
                                                    ["checkcode"] = 2,
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["y"] = 1,
                                                        ["x"] = 2,
                                                        ["w"] = 1018,
                                                        ["h"] = 732,
                                                    },
                                                    ["level"] = 0,
                                                },
                                            },
                                            ["level"] = 0,
                                        },
                                        [3] = {
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW<1>",
                                            ["hidden"] = true,
                                            ["geom"] = {
                                                ["y"] = 18,
                                                ["x"] = 1,
                                                ["w"] = 1022,
                                                ["h"] = 734,
                                            },
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["windowid"] = 10485780,
                                                    ["checkcode"] = 3,
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["y"] = 7,
                                                        ["x"] = 3,
                                                        ["w"] = 1017,
                                                        ["h"] = 720,
                                                    },
                                                    ["level"] = 0,
                                                },
                                            },
                                            ["level"] = 0,
                                        },
                                        [4] = {
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW<3>",
                                            ["hidden"] = true,
                                            ["geom"] = {
                                                ["y"] = 18,
                                                ["x"] = 1,
                                                ["w"] = 1022,
                                                ["h"] = 734,
                                            },
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["windowid"] = 14680135,
                                                    ["checkcode"] = 4,
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["y"] = 0,
                                                        ["x"] = 0,
                                                        ["w"] = 1022,
                                                        ["h"] = 734,
                                                    },
                                                    ["level"] = 0,
                                                },
                                            },
                                            ["level"] = 0,
                                        },
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 15,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [2] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free_glue",
                ["managed"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchpad*",
                ["hidden"] = true,
                ["mode"] = 0,
                ["geom"] = {
                    ["y"] = 144,
                    ["x"] = 192,
                    ["w"] = 640,
                    ["h"] = 480,
                },
                ["level"] = 1024,
            },
        },
    },
}

