#!/bin/zsh
# vim: nolist
export PATH="$HOME/bin:$HOME/local/bin:$HOME/.cabal/bin:$PATH"
xrdb .Xdefaults

# The following broke with systemd v208.
#if [[ -x /bin/systemd ]]; then
#	echo "Systemd mode starting in $PWD"
#	exec /bin/systemd --user --unit=graphical.target
#fi

#xmodmap ~/.xmodmaprc
function first_executable() {
    for x in "$@"; do
	if command which "$x" &>/dev/null; then
	    echo "$x"
	    return 0
	fi
    done
    return 1
}
function have() {
	command which "$1" &>/dev/null
}

if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
	eval `dbus-launch --sh-syntax --exit-with-session`
fi

eval $(gpg-agent --daemon --enable-ssh-support)

/usr/bin/setxkbmap -option '' -option 'grp:shifts_toggle,lv3:ralt_switch,compose:ralt' 'us,de'

emacs --daemon

have synergys && synergys  -1 -a 127.0.0.1:24800
have btsync && btsync --config /home/thequux/.config/btsync.conf

case `hostname -f` in
    peewee.*)
	xbattbar -ca &
	xscreensaver -no-splash &
	google-chrome --user-data-dir=$HOME/.no-git-control/chromium/default &
	nm-applet &
	psi-plus &
	gmpc &
	wmname compiz
	WM=awesome
	;;
    krogoth.dorm-thequux.com)
	WM=xmonad
	;;
    vulcan.home.thequux.com)
	WM=awesome
	#xmobar &
	fbsetbg -l
	;;
    *)
	WM="`first_executable xmonad fluxbox ion3 fluxbox twm`"
	;;
esac
	
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
$WM &>.xsession-errors-wm

exec xterm
#exec startxfce4
