#!/bin/bash
# vim: nolist
export PATH="$HOME/bin:$HOME/local/bin:$HOME/.cabal/bin:$PATH"
if [[ -x /bin/systemd ]]; then
	echo "Systemd mode starting in $PWD"
	exec /bin/systemd --user --unit=graphical.target
fi

echo "foo"
xmodmap ~/.xmodmaprc
function first_executable() {
    for x in "$@"; do
	if command which "$x" &>/dev/null; then
	    echo "$x"
	    return 1;
	fi
    done
}

if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
	eval `dbus-launch --sh-syntax --exit-with-session`
fi

eval $(gpg-agent --daemon --enable-ssh-support)

setxkbmap -option 'grp:shifts_toggle,lv3:ralt_switch' 'us,de'

emacs --daemon

case `hostname -f` in
    peewee.thequux.com)
	xbattbar-acpi &
	xscreensaver -no-splash &
	xchat &
	pidgin &
	gmpc &
	WM=awesome
	;;
    krogoth.dorm-thequux.com)
	WM=xmonad
	;;
    vulcan.home.thequux.com)
	WM=awesome
	xmobar &
	fbsetbg -l
	;;
    *)
	WM="`first_executable xmonad fluxbox ion3 fluxbox twm`"
	;;
esac
	
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
xrdb .Xdefaults
$WM &>.xsession-errors-wm

exec xterm
#exec startxfce4
