# -*- mode: sh -*-

# THIS FILE MUST REMAIN IDEMPOTENT! As it is modified, it can be rerun
# automatically, and it bothers me when various path envvars grow
# without bound.

# _tq_envfile_ts contains a list of the timestamps of various init
# files. It is used by the reinit command in zshrc and in the shell
# prompt.
typeset -A _tq_envfile_ts
function _tq_update_envfile_ts() {
    local f=$1
    _tq_envfile_ts[$f]="$(stat -Lc "%Y" "$f")"
}

_tq_update_envfile_ts "$HOME/.zshenv"

if ! (( ${+SYSTEM_PATH} )); then
   export SYSTEM_PATH="$PATH"
else
   PATH="$SYSTEM_PATH"
fi

export EC2_HOME=$HOME/local/opt/ec2-api-tools-1.6.6.0
path=(
	${EC2_HOME}/bin
	/home/thequux/.rvm/bin
	/home/thequux/local/bin
	/home/thequux/.../bin
	$path
)

export GOPATH="${HOME}/Projects/go"
export GOBIN="${HOME}/local/bin"
export P4CONFIG="${HOME}/.p4config"
export URBIT_HOME=/home/thequux/src/urbit/urb
export GS_LIB="${HOME}/local/share/ghostscript"
export LD_LIBRARY_PATH="$HOME/lib:$HOME/local/lib:/usr/local/lib:/usr/lib/llvm-3.2/lib"

export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
