#!/bin/bash

if [[ $1 == "--about" ]]; then
	echo "Bump the \"Make git commit\" habit on HRPG"
	exit 0
fi

PATH="$HOME/.../bin:$PATH"
CFG="$HOME/.config/habitrpg/config"

[[ -e $CFG ]] && curl -X POST \
	-H "X-Api-User: $(initool $CFG Auth UserID)" \
	-H "X-Api-Key: $(initool $CFG Auth APIToken)" \
	https://habitrpg.com/api/v2/user/tasks/git-commit/up &>/dev/null
