
(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(LaTeX-command "latex")
 '(TeX-PDF-mode nil)
 '(auto-completion-syntax-alist (quote (reject . word)))
 '(c-basic-offset 8)
 '(completion-resolve-behaviour (quote reject))
 '(completion-use-hotkeys nil)
 '(cperl-autoindent-on-semi t)
 '(cperl-font-lock t)
 '(cperl-hairy nil)
 '(cperl-indent-wrt-brace nil)
 '(cperl-lazy-help-time 3)
 '(delete-old-versions t)
 '(font-lock-verbose nil)
 '(frame-background-mode (quote dark))
 '(haskell-doc-show-global-types t)
 '(haskell-font-lock-symbols nil)
 '(haskell-mode-hook (quote (turn-on-haskell-indent turn-on-eldoc-mode)))
 '(inhibit-startup-screen t)
 '(jit-lock-context-time 0.1)
 '(kept-new-versions 4)
 '(kept-old-versions 3)
 '(mouse-autoselect-window t)
 '(mouse-yank-at-point t)
 '(muse-project-alist (quote (("WikiPlanner" ("~/plans" "index")))) t)
 '(predictive-add-to-dict-ask nil t)
 '(predictive-auto-add-to-dict t t)
 '(predictive-auto-learn t t)
 '(predictive-dict-autosave t)
 '(predictive-flush-auto-learn-delay 1)
 '(predictive-main-dict (quote dict-local) t)
 '(predictive-use-buffer-local-dict t)
 '(prolog-program-name "gprolog")
 '(safe-local-variable-values (quote ((tab-always-indent) (haskell-literate . latex) (add-log-time-zone-rule . t))))
 '(scalable-fonts-allowed t)
 '(scheme-program-name "mzscheme")
 '(show-paren-mode t nil (paren))
 '(show-paren-style (quote mixed))
 '(standard-indent 8)
 '(vc-handled-backends (quote (RCS CVS SVN SCCS HG Arch MCVS)))
 '(version-control t))
(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(default ((t (:stipple nil :background "grey20" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 101 :width normal :foundry "unknown" :family "Monaco"))))
 '(cursor ((t (:background "white"))))
 '(custom-button ((((type x w32 mac) (class color)) (:background "lightgrey" :foreground "black" :box (:line-width -1 :style released-button)))))
 '(fixed-pitch ((t (:foundry "unknown" :family "Monaco"))))
 '(font-lock-builtin-face ((((class color) (min-colors 88) (background dark)) (:foreground "#ff80ff" :weight bold))))
 '(font-lock-comment-face ((((class color) (min-colors 88) (background dark)) (:foreground "#80a0ff"))))
 '(font-lock-constant-face ((((class color) (min-colors 88) (background dark)) (:foreground "#ff80ff"))))
 '(font-lock-function-name-face ((((class color) (min-colors 88) (background dark)) (:foreground "#40ffff" :weight bold))))
 '(font-lock-keyword-face ((((class color) (min-colors 88) (background dark)) (:foreground "#ffff80" :weight bold))))
 '(font-lock-string-face ((((class color) (min-colors 88) (background dark)) (:background "black" :foreground "#ffa0a0"))))
 '(font-lock-type-face ((((class color) (min-colors 88) (background dark)) (:foreground "Green" :weight bold))))
 '(font-lock-variable-name-face ((((class color) (min-colors 88) (background dark)) (:foreground "#ff6" :weight bold))))
 '(fringe ((((class color) (background dark)) (:background "grey40"))))
 '(highlight ((t (:background "grey60"))))
 '(isearch ((((class color) (min-colors 88) (background dark)) (:inverse-video nil))))
 '(lazy-highlight ((((class color) (min-colors 88) (background dark)) (:background "yellow" :foreground "black"))))
 '(mode-line ((t (:background "grey80" :foreground "Black" :box (:line-width -1 :color "grey" :style released-button)))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :style released-button)))))
 '(mode-line-inactive ((default (:inherit mode-line)) (((class color) (min-colors 88) (background dark)) (:background "grey70" :box nil :weight light))))
 '(mouse ((t (:background "White"))))
 '(region ((t (:foreground "grey60" :inverse-video t))))
 '(tooltip ((((class color)) (:inherit variable-pitch :background "lightyellow" :foreground "black" :foundry "unknown" :family "DejaVu Sans"))))
 '(underline ((((supports :underline t)) (:inherit default :underline t))))
 '(variable-pitch ((t (:family "DejaVu Sans")))))

