-- This file has been generated by Ion. Do not edit.
return {
    [1] = "menu.mainmenu:session/restart-xmonad",
    [2] = "menu.mainmenu:session/restart",
    [3] = "run:gmpc",
    [4] = "menu.mainmenu:session/exit",
    [5] = "man:",
    [6] = "yesno:y",
    [7] = "menu.mainmenu:styles/look_greenlight",
}

